### PR TITLE
Migrate to Bevy 0.12 and upgrade stl_io

### PR DESCRIPTION
**Pull request by azazdeaz**
Hi There! Thanks a lot for this lib! :heart: 

This PR migrates to Bevy 0.12 and upgrades stl_io.

Let me know if you need any changes on this.

### CODE REVIEW

**Comment by nilclass** [comment]
@azazdeaz thank you for your contribution, much appreciated :heart:

**Comment by nilclass** [comment]
Your changes are published to crates.io now, as `bevy_stl@0.12`

**Comment by johnbchron** [comment]
Looks like the wireframe feature is borked on this version @nilclass :
```
error[E0425]: cannot find value `load_context` in this scope
  --> /Users/jlewis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_stl-0.12.0/src/lib.rs:44:13
   |
44 |             load_context.labeled_asset_scope("wireframe".to_string(), |_load_context| {
   |             ^^^^^^^^^^^^
   |
help: a local variable with a similar name exists, consider changing it
   |
35 |         load_context: &'a mut LoadContext,
   |         ~~~~~~~~~~~~
```

**Comment by azazdeaz** [comment]
@johnbchron sorry about that! Fixed in https://github.com/nilclass/bevy_stl/pull/13

**Pull request merged**
